# Generated by Django 3.1.7 on 2021-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Поле'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, max_length=70, null=True, verbose_name='Ссылка'),
        ),
    ]
