# Generated by Django 3.1.7 on 2021-04-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210419_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('You have no rights', 'Проверка профиля')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
