# Generated by Django 3.1.7 on 2021-04-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210419_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('You_have_no_rights', 'Проверка профиля')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
