# Generated by Django 3.1.7 on 2021-03-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210329_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='webapp.project'),
            preserve_default=False,
        ),
    ]
