# Generated by Django 3.1.7 on 2021-04-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('update_delete_user', 'редактировать пользователя')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
